version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28 
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - add_ssh_keys:
          fingerprints:
            - "05:a7:28:bc:8f:93:8e:7a:6a:70:99:71:57:98:b3:1c"      
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Run Unit Tests
          command: ./gradlew test -i
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
